.class public final LX/FGD;
.super Lkotlin/coroutines/jvm/internal/ContinuationImpl;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lcom/vega/draft/export/DraftExporter;->a$0(Lcom/vega/draft/export/DraftExporter;Lorg/json/JSONObject;Lkotlinx/coroutines/channels/Channel;Ljava/lang/String;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = null
.end annotation

.annotation runtime Lkotlin/coroutines/jvm/internal/DebugMetadata;
    c = "com.vega.draft.export.DraftExporter"
    f = "DraftExporter.kt"
    i = {
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x0,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x1,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x2,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x3,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x4,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x5,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x6,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x7,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x8,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0x9,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xa,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xb,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xc,
        0xd,
        0xd,
        0xd,
        0xd,
        0xd,
        0xd,
        0xe,
        0xe,
        0xe,
        0xe,
        0xe,
        0xe,
        0xe,
        0xf,
        0xf,
        0xf,
        0xf,
        0xf,
        0xf,
        0x10,
        0x10,
        0x10,
        0x10,
        0x10,
        0x10,
        0x11,
        0x11,
        0x11,
        0x11,
        0x11,
        0x11,
        0x11,
        0x11,
        0x12,
        0x12,
        0x12,
        0x12,
        0x12,
        0x12,
        0x13,
        0x13,
        0x13,
        0x13,
        0x13,
        0x13,
        0x14,
        0x14,
        0x14,
        0x14,
        0x14,
        0x14,
        0x14,
        0x15,
        0x15,
        0x15,
        0x15,
        0x15,
        0x15,
        0x15,
        0x15,
        0x16,
        0x16,
        0x16,
        0x16,
        0x16,
        0x16,
        0x16,
        0x17,
        0x17,
        0x17,
        0x17,
        0x17,
        0x17,
        0x18,
        0x18,
        0x18,
        0x18,
        0x18,
        0x18,
        0x19,
        0x19,
        0x19,
        0x19,
        0x19,
        0x19,
        0x1a,
        0x1a,
        0x1a,
        0x1a,
        0x1a,
        0x1a,
        0x1b,
        0x1b,
        0x1b,
        0x1b,
        0x1b,
        0x1b,
        0x1b,
        0x1b,
        0x1c,
        0x1c,
        0x1c,
        0x1c,
        0x1c,
        0x1c,
        0x1d,
        0x1d,
        0x1d,
        0x1d,
        0x1d
    }
    l = {
        0x1d3,
        0x1e0,
        0x1e6,
        0x1ef,
        0x1f9,
        0x207,
        0x213,
        0x221,
        0x22d,
        0x23d,
        0x24b,
        0x25a,
        0x268,
        0x27d,
        0x28e,
        0x298,
        0x2a6,
        0x2b8,
        0x2c8,
        0x2da,
        0x2e9,
        0x2f6,
        0x305,
        0x30e,
        0x31e,
        0x331,
        0x33e,
        0x34d,
        0x35b,
        0x367
    }
    m = "handleMaterialPath"
    n = {
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "originVideoPath",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "videoAlgorithm",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "videoAlgorithm",
        "mouthShapeDriver",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "videoAlgorithm",
        "mouthShapeDriver",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2411",
        "video",
        "paths",
        "i",
        "idx",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2412",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2413",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2414",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2415",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2416",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2417",
        "tracking",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2417",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2418",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2419",
        "animList",
        "i",
        "idx",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2420",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2421",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2422",
        "textTemplate",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2422",
        "resources",
        "i",
        "idx",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2423",
        "handwrite",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2423",
        "i",
        "materials",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2426",
        "i",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2433",
        "digitalHumanJson",
        "i",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2433",
        "digitalHumanJson",
        "i",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2433",
        "digitalHumanJson",
        "ttsMetaJsonArray",
        "i",
        "index",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2433",
        "digitalHumanJson",
        "i",
        "messageChannel",
        "exportDir",
        "subDirPrefix",
        "$this$handleMaterialPath_u24lambda_u2433",
        "i"
    }
    s = {
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "L$7",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "L$9",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "L$9",
        "L$10",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "L$9",
        "L$10",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "L$7",
        "I$0",
        "I$2",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "I$0",
        "I$2",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$8",
        "I$0",
        "I$2",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "L$6",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$3",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$4",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$4",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$4",
        "L$5",
        "L$6",
        "I$0",
        "I$2",
        "L$0",
        "L$1",
        "L$2",
        "L$4",
        "L$5",
        "I$0",
        "L$0",
        "L$1",
        "L$2",
        "L$4",
        "I$0"
    }
.end annotation


# instance fields
.field public a:Ljava/lang/Object;

.field public b:Ljava/lang/Object;

.field public c:Ljava/lang/Object;

.field public d:Ljava/lang/Object;

.field public e:Ljava/lang/Object;

.field public f:Ljava/lang/Object;

.field public g:Ljava/lang/Object;

.field public h:Ljava/lang/Object;

.field public i:Ljava/lang/Object;

.field public j:Ljava/lang/Object;

.field public k:Ljava/lang/Object;

.field public l:I

.field public m:I

.field public n:I

.field public o:I

.field public synthetic p:Ljava/lang/Object;

.field public final synthetic q:Lcom/vega/draft/export/DraftExporter;

.field public r:I


# direct methods
.method public constructor <init>(Lcom/vega/draft/export/DraftExporter;Lkotlin/coroutines/Continuation;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcom/vega/draft/export/DraftExporter;",
            "Lkotlin/coroutines/Continuation<",
            "-",
            "LX/FGD;",
            ">;)V"
        }
    .end annotation

    iput-object p1, p0, LX/FGD;->q:Lcom/vega/draft/export/DraftExporter;

    invoke-direct {p0, p2}, Lkotlin/coroutines/jvm/internal/ContinuationImpl;-><init>(Lkotlin/coroutines/Continuation;)V

    return-void
.end method


# virtual methods
.method public final invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object;
    .locals 5

    iput-object p1, p0, LX/FGD;->p:Ljava/lang/Object;

    iget v1, p0, LX/FGD;->r:I

    const/high16 v0, -0x80000000

    or-int/2addr v1, v0

    iput v1, p0, LX/FGD;->r:I

    iget-object v0, p0, LX/FGD;->q:Lcom/vega/draft/export/DraftExporter;

    const/4 v1, 0x0

    move-object v2, v1

    move-object v3, v1

    move-object v4, v1

    invoke-static/range {v0 .. v5}, Lcom/vega/draft/export/DraftExporter;->a$0(Lcom/vega/draft/export/DraftExporter;Lorg/json/JSONObject;Lkotlinx/coroutines/channels/Channel;Ljava/lang/String;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;

    move-result-object v0

    return-object v0
.end method
